server:
  port: 9000
logging:
  level:
    root: WARN
    com.skillzstreet: DEBUG 
    #org.springframework.security: DEBUG
security:
#  oauth2:
#    resource:
#      jwt:
#        keyValue: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqmG80/bWYfVzbX2jjDCP2itWth2kRhoue6BfXt/FX+Ih1YuDrO8EvFjCa14aO7VUmscNmAaauWykygxfc7gM5bPSiH0rM31ZyXBtqvT31CxGpYOKz+fjLof2Q8akXi721nIsvMbuze6MfnbSqDnP9Bi1KZEItVOvhQR3K11ov7nTLTL5bqqNwL6WesmGnc7y8yIRPnZyUc1JSPeM0rv515IoEX6kVSdQ9hT7RCNqUSYwzA/XkP9IIqSuB4qQlhck3/JgSKM0j0RuhvNuG/7aFuTYe1G8UjvNmOUp8tJo3AX5cZYlagpTkvyTzcKYlts8a9EVXRKP52qfS6C4Rm5UgQIDAQAB
#          -----END PUBLIC KEY-----

  jwt:
    public-key: classpath:public.txt
         

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    hibernate:
      ddl-auto: validate
    show-sql: true
    
# ===============================
# = DATA SOURCE
# ===============================
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1


master:
  datasource:
    url: jdbc:postgresql://localhost:5431/talentspy
    username: talentspy
    password: hpb0vzrU7jKiKtQN
    driverClassName: org.postgresql.Driver
    #connectionTimeout: 20000
    maxPoolSize: 10
    #idleTimeout: 300000
    #minIdle: 10
    poolName: masterdb-connection-pool