server:
  port: 9002

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArumtig9U/MHMO0cHUp24e7AL6e8WkLxJpLu2yZV4/Fb3vAqjwZDSmf5VwnsIGKxU5BYZGQK9KyDgn8qaOm+eXyhbymcIU3gH3MwFFo+kTjv4P57BpIU2M5nTL8K2ulFogm1Wbc83f44jw+XU99N8UUUZad4EBQAkULyHBxighBhXR8iEshAeWwitHu1tlTYccdwuHcvsKc0n+y2Yw63AB5+A6cAAvaVLQETkFcpQURnafQzRFsEFEx/Cb7pH3Jl0+QgE+PvBLiZQtU3K0rNBjB40vCgw06ed40F9Prchavxqims65TrqZWLAr7lUggwZAT+Ca/B77a3LGbeRSfDiewIDAQAB
          -----END PUBLIC KEY-----

spring:
  rabbitmq:
    hostname: localhost
    port: 5672
    username: admin
    password: admin

  
# ===============================
# = DATA SOURCE
# ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password


# Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================

# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager).

# Show or not log for each sql query
  jpa:
    show-sql: false

# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
    hibernate:
      ddl-auto: update

# Naming strategy
# spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      

# Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect



axon:
  amqp:
    exchange: AmqpEvents

  eventhandling:
    processors:
      user:
        source: userEventsMethod


lms:
  hostname: http://ec2-18-140-93-224.ap-southeast-1.compute.amazonaws.com      